
name: SDS integration test on Arm Virtual Hardware
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
env:
  ARMLMD_LICENSE_FILE: /opt/data.dat
  ARM_TOOL_VARIANT: ult
  AC6_TOOLCHAIN_6_18_0: /opt/armcompiler/bin
  LD_LIBRARY_PATH: /opt/VHT
  AVH_PATH: /opt/VHT

jobs:
  build:
    name: Build and Run
    runs-on: AVH-Runner

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Build demo using CMSIS toolbox
        working-directory: ./demo
        run: |
          ./tool-inventory.sh
          . <(curl https://aka.ms/vcpkg-init.sh -L)
          vcpkg activate
          cbuild Demo.csolution.yml --packs --update-rte --configuration .debug+AVH
#          VHT_MPS3_Corstone_SSE-300 -f Board/AVH_MPS3_Corstone-300/fvp_config.txt -V ../sensor/vsi/python out/Demo/AVH/Debug/Debug+AVH.axf
        
