
name: SDS integration test on Arm Virtual Hardware
on: [workflow_dispatch]

jobs:
  ci_build_and_test_loopback:
  
    runs-on: Arm-Virtual-Hardware
  
    env:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/armcompiler/bin:/opt/gcc-arm-11.2-2022.02-x86_64-arm-none-eabi/bin:/opt/VHT-1.1.2
      ARMLMD_LICENSE_FILE: /opt/data.dat
      ARM_TOOL_VARIANT: ult
      LD_LIBRARY_PATH: /opt/VHT-1.1.2
    
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v3
    
      - name: Build demo using CMSIS toolbox
      - working-directory: ./demo
      - run: |
          csolution list packs -s Demo.csolution.yml -m >packs.txt
          cpackget add -f packs.txt
          csolution convert -s Demo.csolution.yml
          cbuild Demo.Debug+AVH.cprj
          VHT_MPS3_Corstone_SSE-300 -f Board/AVH_MPS3_Corstone-300/fvp_config.txt -V ../sensor/vsi/python out/Demo/AVH/Debug/Debug+AVH.axf
        
        
     
